### ISSUE TITLE
SB_WP_URL and APIKEY does not get logged during Install

### ISSUE THREAD

**Issue by 404UserNotFound** [Sarabveer/SourceBans-Fork#89]
common issue, been posted on alliedmods in the thread numerous times. somehow, the installation doesn't properly record wp-url and API key and results in an error during installation. fix is to add the shit manually to the config.php file.

should be fixed so people don't have to manually add it but i don't know where it's fucked up.

**Comment by Sarabveer** [comment]
Works for me

**Comment by 404UserNotFound** [comment]
well maybe people were using the old thread version cause that's where it occurred.

**Comment by Sarabveer** [comment]
lol idk

worked on 1.5.3 for me

**Comment by driz** [comment]
the error is:
Notice: Undefined index: apikey in /var/www/banned/install/template/page.5.php on line 50
Notice: Undefined index: sb-wp-url in /var/www/banned/install/template/page.5.php on line 51

adding the keys into config.php following installation does resolve the error. Experienced this in 1.5.3.

**Comment by Sarabveer** [comment]
Just pushed an update (b98963c73433674f4f5050e2384721f09343c53b)

I just tested the installer on my webserver, it inserts the URL and the API Key correctly.  
FYI: I am using **Apache/2.4.17 (Win64) OpenSSL/1.0.2e PHP/5.6.16** as my current webserver.

**Comment by Sarabveer** [comment]
Can anyone test the dev version out?

**Comment by Sarabveer** [comment]
Since there has been no response, I will close the issue since it looks like it has been fixed from my end.

I never had the problem in the first place.

**Comment by groseb** [comment]
Just installed sourcebans (v1.5.3) and I got the error : 
![image](https://cloud.githubusercontent.com/assets/5783476/12743883/37c4df96-c991-11e5-941e-13048f6b636d.png)
I'm running php 5.6.17 and nginx 1.9.10

**Comment by Sarabveer** [comment]
lookong into this

**Comment by Sarabveer** [comment]
I cannot come up with any conclusion, I have tried so many times, and It always works, dunno whats the problem.

I'm gonna close this issue.
